---
name: Build package repository
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Build Satis package repository
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/composer/satis:latest
          options: -v ${{ github.workspace }}:/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/output
          cname: composer.rpun.dev
