---
name: Build package repository
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Pull Docker image
        run: |
          docker pull ghcr.io/composer/satis:latest
      - name: Build Satis package repository
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          docker run --rm --user "$(id -u):$(id -g)" -v $WORKSPACE_PATH:/build ghcr.io/composer/satis:latest
      - name: Verify build output
        run: ls -la ${{ github.workspace }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/output
          cname: composer.rpun.dev
